### ISSUE TITLE
Uploading an exam with multiple categories only shows Bloom's (or whichever is the first category in the csv)

### ISSUE THREAD

**Issue by mlee4242** [yucissy/Bloom#19]
On the graphs, it only shows blooms instead of showing Bloom's + the other main category.

**Comment by yucissy** [comment]
@katiewhan there is a problem in /getAllAggregate -- the return object doesn't contain non-bloom's categories

**Comment by katiewhan** [comment]
Backend fixed, frontend work needed to display multiple categories. @yucissy
